Numpy Basic Assignment

In [1]:
import numpy as np
list_ = [1,2,3,4,5]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [2]:
list_

[1, 2, 3, 4, 5]

In [3]:
array_list

array([1, 2, 3, 4, 5])

In [4]:
print(type(list_))

<class 'list'>


In [5]:
print(type(array_list))

<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [6]:
for i in list_:
    print(type(list_))

<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>


In [7]:
for i in array_list:
    print(type(array_list))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


Q3. Considering the following changes in the variable, array_list

In [8]:
array_list = np.array(object = list_, dtype = int)

In [9]:
array_list

array([1, 2, 3, 4, 5])

In [10]:
for i in array_list:
    print(type(array_list))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


Q4. Write a code to find the following characteristics of variable, num_array

In [11]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [14]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [17]:
num_array.size

6

In [18]:
num_array.shape

(2, 3)

In [21]:
import numpy.matlib as nm

Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [39]:
a5=nm.zeros((3,3))

In [40]:
a5

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [41]:
print(type(a5))

<class 'numpy.matrix'>


In [42]:
a5.shape

(3, 3)

In [43]:
a5.size

9

Create an identity matrix of shape (5,5) using numpy functions?

In [35]:
A6=nm.eye(5)

In [38]:
A6.shape

(5, 5)